# Generated by Django 3.1 on 2020-08-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=800, unique=True)),
                ('css_selector', models.CharField(max_length=200)),
                ('interval', models.PositiveSmallIntegerField()),
                ('interval_unit', models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days')], max_length=7)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('decimal_separator', models.CharField(max_length=1)),
                ('parse_func', models.TextField(default="def parse_price(x: str, decimal_separator: str) -> float:\n    valid_chars = {\n        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',\n        decimal_separator,\n    }\n    trimmed = ''.join(c for c in x if c in valid_chars)\n    return float(trimmed.replace(decimal_separator, '.'))\n")),
            ],
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_results', to='tracker.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='price_parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.priceparser'),
        ),
        migrations.CreateModel(
            name='HtmlNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('run_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_nodes', to='tracker.runresult')),
            ],
        ),
    ]
