# Generated by Django 3.1 on 2020-08-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=800, unique=True)),
                ('html_filter_kwargs', models.TextField(blank=True)),
                ('interval', models.PositiveSmallIntegerField()),
                ('interval_unit', models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days')], max_length=7)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_results', to='tracker.page')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('run_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='html_nodes', to='tracker.runresult')),
            ],
        ),
    ]
