# Generated by Django 3.1 on 2020-08-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
